# Import numpy for math operations
import numpy as np
# Import warnings to suppress messy output logs
import warnings
# Import standard breast cancer classification dataset
from sklearn.datasets import load_breast_cancer
# Import splitting utility for test/train segmentation
from sklearn.model_selection import train_test_split
# Import central LogisticRegression model algorithm
from sklearn.linear_model import LogisticRegression
# Import accuracy_score for numerical validation of model health
from sklearn.metrics import accuracy_score
# Import warnings generated by unfitted models
from sklearn.exceptions import ConvergenceWarning

# Ignore convergence warnings for cleaner output during the demo
warnings.filterwarnings("ignore", category=ConvergenceWarning)

# --- Environment Setup ---
# Add the parent directory of self_healing_plugin to the Python path
# so we can import the package modules even if not installed via pip.
import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "../..")))

# Import HealingContext container
from self_healing_plugin.core.context import HealingContext
# Import SelfHealingPlugin central logic
from self_healing_plugin.core.plugin import SelfHealingPlugin
# Import basic numeric mean shift math logic
from self_healing_plugin.detectors.simple_drift import SimpleMeanShiftDetector
# Import mathematical probability entropy checker
from self_healing_plugin.detectors.overconfidence import OverconfidenceDetector
# Import deterministic rule converter
from self_healing_plugin.errors.error_classifier import RuleBasedErrorClassifier
# Import simple static mapping logic tree
from self_healing_plugin.policies.healing_policy import DefaultHealingPolicy
# Import pre-processor check guard
from self_healing_plugin.safety.data_guard import DataValidityGuard
# Import dictionary-to-sklearn translator
from self_healing_plugin.adapters.sklearn_adapter import SklearnAdapter

# Standard explicit printout logger
def log_event(ctx):
    # Print the core error type recognized and the executed response
    print(f"\n[PLUGIN ACTION] Detected: {ctx.error_type} | Action Taken: {ctx.result}")
    # Print out the raw numeric values observed during the logic cycle
    print(f"               Signals: {ctx.signals}")

# Main execution logic function
def main():
    # Print header decoration
    print("=========================================================")
    # Print exact demonstration script title
    print("🤖 Self-Healing Plugin - Logistic Regression Demonstration")
    # Print footer decoration
    print("=========================================================")

    # 1. Load real dataset
    print("\nLoading Breast Cancer dataset...")
    # Read breast cancer table from sklearn datasets
    data = load_breast_cancer()
    # Separate features and target classifications
    X, y = data.data, data.target
    
    # Split: Train, Validation (clean stream), Drifted Stream
    # We use a smaller test size here just to give LogisticRegression enough data to converge
    X_train, X_stream, y_train, y_stream = train_test_split(X, y, test_size=0.4, random_state=42)
    # Re-split the remaining 40% logically into validation and drift
    X_val, X_drift, y_val, y_drift = train_test_split(X_stream, y_stream, test_size=0.5, random_state=42)

    # 2. Train baseline model
    print("\n🏋️ Training initial baseline model (LogisticRegression)...")
    # max_iter is kept relatively low to realistically simulate a model that might struggle on heavily drifted data
    model = LogisticRegression(random_state=42, max_iter=200)
    # Start adjusting internal matrices and boundaries
    model.fit(X_train, y_train)
    
    # Check baseline initial capabilities on unmodified inputs
    initial_acc = accuracy_score(y_val, model.predict(X_val))
    # Render final string out 
    print(f"✅ Baseline Accuracy on Clean Data: {initial_acc:.2%}")

    # Wrap model in a holder so the adapter can update it dynamically
    model_holder = {"model": model}

    # 3. Setup self-healing plugin
    print("\n⚙️ Setting up Self-Healing Plugin...")
    # Encapsulate adapter for retraining operations
    adapter = SklearnAdapter(model_holder)
    # Stand up a new plugin orchestration instance
    plugin = SelfHealingPlugin(
        detectors=[
            # Detects if the mean of the incoming data shifts drastically from the expected baseline
            SimpleMeanShiftDetector(threshold=0.5), 
            # Detects if the internal probabilities are >90% confident when wrong
            OverconfidenceDetector(entropy_threshold=0.1)
        ],
        # String translator rules mapping detector events into literal string enums
        error_classifier=RuleBasedErrorClassifier(),
        # Default behavior engine triggering block vs retrain
        policy_engine=DefaultHealingPolicy(adapter),
        # Mandatory boolean checking ensuring validity
        safety_guards=[DataValidityGuard()],
        # Plug the print function pointer defined above
        logger=log_event
    )

    # 4. Scenario: Normal Data Execution
    print("\n--- 🟢 SCENARIO 1: Processing Normal Data Stream ---")
    # Mount execution context containing clean validations
    context_normal = HealingContext(
        # Bind the live proxy object pointer
        model=model_holder["model"],
        # Provide unadulterated X validation data
        X=X_val,
        # Provide clean ground truth 
        y=y_val, 
        # Attach the historic baselines
        metadata={"X_train": X_train, "y_train": y_train}
    )
    # The plugin monitors this clean batch. It might detect Overconfidence but standard policy usually BLOCKS that.
    plugin.monitor(context_normal)
    # Check model performance to ensure standard accuracy was unaffected
    current_acc = accuracy_score(y_val, model_holder["model"].predict(X_val))
    # Render confirmation output
    print(f"📊 Accuracy remains steady: {current_acc:.2%}")

    # 5. Scenario: Data Drift Execution
    print("\n--- 🔴 SCENARIO 2: Sudden Data Drift Occurs! ---")
    # Introduce severe drift (simulating sensor degradation or new population)
    # By shifting the mean drastically, the Logistic Regression decision boundary becomes wildly inaccurate
    X_drift_severe = X_drift + np.mean(X_train, axis=0) * 1.5 
    
    # Record accuracy BEFORE healing to visualize the performance destruction
    degraded_acc = accuracy_score(y_drift, model_holder["model"].predict(X_drift_severe))
    # Warn standard out that accuracy is dead
    print(f"⚠️ Model accuracy PLUMMETED to {degraded_acc:.2%} due to data drift!")

    # Pass the drifted data to the plugin for monitoring
    context_drift = HealingContext(
        # Same proxy map injected
        model=model_holder["model"],
        # Input specifically trashed X parameters
        X=X_drift_severe,
        # Providing new true labels so the plugin can perform retraining operations to adjust boundary
        y=y_drift, 
        # Standard metrics for deviation mathematical basis
        metadata={"X_train": X_train, "y_train": y_train}
    )
    
    # Indicate healing protocol instantiation
    print("🔍 Plugin monitoring stream... (Detecting drift and attempting recovery...)")
    # Engage event loop lifecycle
    plugin.monitor(context_drift)
    
    # 6. Evaluate healed model
    print("\n--- 🟢 SCENARIO 3: Evaluating Healed Model ---")
    # Capture accuracy utilizing the modified memory weights injected via RetrainAction payload
    recovered_acc = accuracy_score(y_drift, model_holder["model"].predict(X_drift_severe))
    # Confirm to human observer
    print(f"✅ Model accuracy recovered to {recovered_acc:.2%} after automated retraining!")
    
    # End decorations
    print("\n=========================================================")
    # Concluding text
    print("Demonstration Complete! The Logistic Regression healed. 🎉")
    # End decorations
    print("=========================================================")

# Enforce strict Python execution parameters mapping to this script scope
if __name__ == "__main__":
    # Fire primary execution routine
    main()
